services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: local
      args:
        - PHP_PREFIX=php84
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: |
      php artisan serve --host=0.0.0.0 --port=8000